# Generated by Django 3.2.5 on 2021-07-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_random_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random',
            name='font_size',
        ),
    ]
