# Generated by Django 3.2.5 on 2021-07-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_remove_random_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='font_size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
